[package]
name = "simplefwd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
core_affinity = "0.8.3"
ctrlc = "3.4.5"
flash = { path = "../../lib/flash-rs" }
tracing-subscriber = "0.3.19"

[lints.rust]
unsafe_code = "forbid"
